apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafkaProperties.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafkaBrokerUser.name }}
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
---